name: Generate Static Files

on:
  push:
    branches:
      - main
    paths:
      - "raw_data/**"
      - "transform.py"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run data generator
        run: |
          python transform.py ./raw_data

      - name: Deploy generated files
        run: |
          git checkout --orphan gh-pages
          git rm -rf .
          mv out/* .
          rm overwritten.log || true
          git config user.name "$GITHUB_ACTOR"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Deploy"
          git push origin gh-pages
